[package]
name = "bread_bot"
version = "0.1.0"
edition = "2021"

[dependencies]
dtt = "0.0.8"
serenity = "0.12"
sqlite = "0.36.1"
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }
